#!/bin/bash
set -eo pipefail

ENV=$1
ACTION=$2
PROCESS={$3:all}

supervisor_action_non_prod() {
    echo -e "\033[92mHOST => sdbs-gcp-$i-$ENV\033[0m"; \
    if [ "$ACTION" == "status" ]; then
      ssh sdbs-gcp-$i.$ENV.nas.native-cloud.com \
      sudo -iu sdbs deployment/bin/sv $ACTION; \
    else
      sudo -ui sdbs deployment/bin/sv/ $ACTION $PROCESS; \
    fi
    sleep 2; \
    echo " ";
}

supervisor_action_prod() {
    echo -e "\033[92mHOST => sdbs-gcp-$i-$ENV\033[0m"; \
    if [ "$ACTION" == "status" ]; then
      ssh sdbs-gcp-$i.nas.native-cloud.com \
      sudo -iu sdbs deployment/bin/sv $ACTION; \
    else
      sudo -ui sdbs deployment/bin/sv/ $ACTION $PROCESS; \
    fi
    sleep 2; \
    echo " ";
}

if [ $ENV == 'dev' ]; then
    for i in $(seq 11 13)
    do
        supervisor_action_non_prod
    done
elif [ $ENV == 'stg' ] ; then
    for i in $(seq 11 13)
    do
        supervisor_action_non_prod
    done
elif [ $ENV == 'prod' ] ; then
    for i in $(seq 11 19)
    do
        supervisor_action_prod
    done
else
    echo -e "Enviroment not found. Try dev, stg or prod"
fi
